apero_user_role_homepage:
    path:     /Users/Roles
    defaults: { _controller: AperoUserBundle:UserRole:index }

apero_user_role_change_role:
    path:    /{username}/Roles/change
    defaults: { _controller: AperoUserBundle:UserRole:change }

apero_user_role_non_validate:
    path:    /Users/non-validate
    defaults: { _controller: AperoUserBundle:UserRole:nonValidate }

apero_user_role_non_admin:
    path:    /Users/non-admin
    defaults: { _controller: AperoUserBundle:UserRole:nonAdmin }

apero_user_amis_homepage:
    path:    /Amis
    defaults: { _controller: AperoUserBundle:Amis:index }