apero_user_role_homepage:
    path:     /Users/Roles
    defaults: { _controller: AperoUserBundle:UserRole:index }

apero_user_role_change_role:
    path:    /{username}/Roles/change
    defaults: { _controller: AperoUserBundle:UserRole:change }

apero_user_role_non_validate:
    path:    /Users/non-validate
    defaults: { _controller: AperoUserBundle:UserRole:nonValidate }

apero_user_role_non_admin:
    path:    /Users/non-admin
    defaults: { _controller: AperoUserBundle:UserRole:nonAdmin }

apero_user_amis_homepage:
    path:    /Amis
    defaults: { _controller: AperoUserBundle:Amis:index }

apero_user_amis_edit:
    path:    /Amis/edit
    defaults: { _controller: AperoUserBundle:Amis:edit }

apero_user_groupe_amis_homepage:
    path:    /GroupesAmis/liste
    defaults: { _controller: AperoUserBundle:GroupeAmis:index }

apero_user_groupe_amis_add:
    path:    /GroupesAmis/add
    defaults: { _controller: AperoUserBundle:GroupeAmis:add }

apero_user_groupe_amis_delete:
    path:    /GroupesAmis/{id}/delete
    defaults: { _controller: AperoUserBundle:GroupeAmis:delete, id: 1 }
    requirements:
        id: \d+

apero_user_groupe_amis_edit:
    path:    /GroupesAmis/{id}/edit
    defaults: { _controller: AperoUserBundle:GroupeAmis:edit, id: 1 }
    requirements:
        id: \d+

apero_user_groupe_amis_view:
    path:    /GroupesAmis/{id}
    defaults: { _controller: AperoUserBundle:GroupeAmis:view, id: 1 }
    requirements:
        id: \d+