parameters:
#    apero_user.example.class: Apero\UserBundle\Example

services:
#    apero_user.example:
#        class: %apero_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
