apero_event_homepage:
    path:     /Event/list
    defaults: { _controller: AperoEventBundle:Event:index }

apero_event_add:
    path:     /Event/add
    defaults: { _controller: AperoEventBundle:Event:add }

apero_event_view:
    path:     /Event/{id}
    defaults: { _controller: AperoEventBundle:Event:view, id: 1 }
    requirements:
        id: \d+

apero_event_edit:
    path:     /Event/{id}/edit
    defaults: { _controller: AperoEventBundle:Event:edit, id: 1 }
    requirements:
        id: \d+

apero_event_delete:
    path:     /Event/{id}/delete
    defaults: { _controller: AperoEventBundle:Event:delete, id: 1 }
    requirements:
        id: \d+

apero_event_join:
    path:    /Event/{id}/join
    defaults: { _controller: AperoEventBundle:Event:join, id: 1 }
    requirements:
        id: \d+

apero_event_leave:
    path:    /Event/{id}/leave
    defaults: { _controller: AperoEventBundle:Event:leave, id: 1 }
    requirements:
        id: \d+

apero_bar_homepage:
    path:     /Bar/list
    defaults: { _controller: AperoEventBundle:Bar:index }

apero_bar_add:
    path:     /Bar/add
    defaults: { _controller: AperoEventBundle:Bar:add }

apero_bar_view:
    path:     /Bar/{id}
    defaults: { _controller: AperoEventBundle:Bar:view, id: 1 }
    requirements:
        id: \d+

apero_bar_edit:
    path:     /Bar/{id}/edit
    defaults: { _controller: AperoEventBundle:Bar:edit, id: 1 }
    requirements:
        id: \d+

apero_bar_delete:
    path:     /Bar/{id}/delete
    defaults: { _controller: AperoEventBundle:Bar:delete, id: 1 }
    requirements:
        id: \d+