parameters:
#    apero_event.example.class: Apero\EventBundle\Example

services:
#    apero_event.example:
#        class: %apero_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
