security:
    encoders:
        Apero\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_VALIDATE:    ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_VALIDATE, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:        ^/login$
            anonymous:      true

        main_register:
            pattern:        ^/register
            anonymous:      true

        main:
            pattern:        ^/
            anonymous:      false
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /Event/list
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                key:        %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
