<?php

namespace Apero\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmisGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmisGroupeRepository extends EntityRepository
{
	public function findbyGroupe($groupeID)
	{
		$qb = $this
			->createQueryBuilder('ua')
		;

		$qb->where('ua.groupe = :groupe')
				->setParameter('groupe', $groupeID)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
