<?php

namespace Apero\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeAmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeAmisRepository extends EntityRepository
{
	public function findbyName($groupeName)
	{
		$qb = $this
			->createQueryBuilder('ga')
		;

		$qb->where('ga.name = :name')
				->setParameter('name', $groupeName)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
