<?php

namespace Apero\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeAmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeAmisRepository extends EntityRepository
{
}
